#!/bin/bash

# This script is useful if passenger is installed under a
# user-specific RVM. This script loads the appropriate rvm environment
# and changes to the project, which triggers gemset loading so that
# passenger is available to the passenger-check.

# Load RVM into a shell session *as a function*
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
  # First try to load from a user install
    source "$HOME/.rvm/scripts/rvm"

elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
  # Then try to load from a root install
    source "/usr/local/rvm/scripts/rvm"

else
  printf "ERROR: An RVM installation was not found.\n"

fi

rack_dir=`ps aux | grep RackApp | grep -v grep | head -n 1 | ruby -ne 'puts $1.strip if ~/Rack.*App: (.*)/'`

if [ -z $rack_dir ] || [ ! -d $rack_dir ] ; then
    >&2 echo "Unable to determine active Passenger project directory."
    exit 1
fi


export rvmsudo_secure_path=1

pushd $rack_dir > /dev/null && rvmsudo /usr/local/bin/passenger-check && popd > /dev/null
